import os
import json
import google.generativeai as genai
from pptx import Presentation
from pptx.util import Inches, Pt

# --------------------------------
# CONFIGURATION
# --------------------------------
API_KEY = os.getenv("GEMINI_API_KEY") 
# MODEL_NAME = "models/gemini-2.5-flash"
MODEL_NAME = "gemini-flash-latest"

if API_KEY:
    genai.configure(api_key=API_KEY)

# --- OUTPUT SETTINGS ---
OUTPUT_FOLDER = r"G:\Project\PDF_TO_TEXT\5_Final_Outputs"

# --- DESIGN SETTINGS: Dynamic Template Folder ---
# 1. Create a folder named 'templates' next to your script.
# 2. Put all your .pptx template files inside this folder.
TEMPLATE_DIR = r"G:\Project\PDF_TO_TEXT\2_OpenCV_OCR\templates"
# -----------------------

# Global variable to hold dynamic template options
DYNAMIC_TEMPLATE_OPTIONS = {}

# --------------------------------
# HELPER: READ FILE
# --------------------------------
def read_text_file(path):
    if not os.path.exists(path):
        with open("input.txt", "w") as f:
            f.write("Artificial Intelligence is changing the world. It helps in healthcare by diagnosing diseases. It helps in finance by detecting fraud.")
        return read_text_file("input.txt")
        
    with open(path, "r", encoding="utf-8") as f:
        return f.read()

# --------------------------------
# CORE: GEMINI LOGIC
# --------------------------------
def get_ai_response(prompt):
    model = genai.GenerativeModel(MODEL_NAME)
    try:
        response = model.generate_content(prompt)
        text = response.text.strip()
        if text.startswith("```json"):
            text = text.replace("```json", "").replace("```", "")
        elif text.startswith("```"):
            text = text.replace("```", "")
        return text
    except Exception as e:
        print(f"Error connecting to AI: {e}")
        return None

def generate_initial_structure(raw_text):
    prompt = f"""
    You are an expert presentation designer. 
    Analyze the following raw text and organize it into a structured PowerPoint presentation.
    
    RAW TEXT:
    {raw_text}
    
    RULES:
    1. Create suitable headings and subheadings for each slide.
    2. Expand on the content to make it presentation-ready.
    3. Output MUST be valid JSON format only.
    4. Structure: A list of objects, where each object has "title" (string) and "content" (list of strings).
    """
    return get_ai_response(prompt)

def update_structure(current_json, user_instruction):
    prompt = f"""
    You are editing a presentation structure based on user feedback.
    CURRENT STRUCTURE (JSON): {current_json}
    USER INSTRUCTION: "{user_instruction}"
    TASK: Modify the JSON structure according to the instruction. Return ONLY valid updated JSON.
    """
    return get_ai_response(prompt)

# --------------------------------
# DISPLAY & EXPORT
# --------------------------------
def print_blueprint(slides_data):
    print("\n" + "="*50)
    print(" 📊 PRESENTATION BLUEPRINT (PREVIEW)")
    print("="*50)
    try:
        data = json.loads(slides_data)
        for i, slide in enumerate(data, 1):
            print(f"\n[SLIDE {i}]: {slide['title']}")
            for bullet in slide['content']:
                print(f"  • {bullet}")
    except:
        print("Error reading the blueprint.")
        return False
    print("\n" + "="*50)
    return True

def create_pptx(slides_data, output_path, template_file=None):
    """Converts the JSON structure into a .pptx using a template if available."""
    try:
        data = json.loads(slides_data)
    except:
        print("❌ Failed to parse data.")
        return

    # --- TEMPLATE LOGIC ---
    if template_file and os.path.exists(template_file):
        print(f"🎨 Using design template: {template_file}")
        prs = Presentation(template_file)
    else:
        print("⚪ Using default blank design.")
        prs = Presentation()
    # ----------------------

    # 1. Create Title Slide
    try:
        title_slide_layout = prs.slide_layouts[0] 
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        
        main_title = data[0]['title'] if data else "Presentation"
        title.text = main_title
        subtitle.text = f"Generated by Gemini"
    except Exception as e:
        print(f"⚠️ Warning: Could not create standard title slide (Template might differ). {e}")

    # 2. Create Content Slides
    # Use layout[1] as the standard Title and Content slide
    bullet_slide_layout = prs.slide_layouts[1] 
    
    for entry in data:
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        
        # Set Title
        try:
            title_shape = shapes.title
            title_shape.text = entry.get('title', 'Untitled')
        except:
            pass 
        
        # Set Bullets
        try:
            body_shape = shapes.placeholders[1]
            tf = body_shape.text_frame
            tf.word_wrap = True
            tf.clear() 

            for point in entry.get('content', []):
                p = tf.add_paragraph()
                p.text = point
                p.level = 0
        except:
            print(f"⚠️ Warning: Could not place text on slide '{entry.get('title')}'")

    prs.save(output_path)
    print(f"\n💾 Presentation saved successfully: {output_path}")

# --------------------------------
# NEW: DYNAMIC TEMPLATE LOADING
# --------------------------------
def load_template_options():
    """Scans the TEMPLATE_DIR for .pptx files and populates DYNAMIC_TEMPLATE_OPTIONS."""
    global DYNAMIC_TEMPLATE_OPTIONS
    DYNAMIC_TEMPLATE_OPTIONS = {}
    
    # Ensure the directory exists
    os.makedirs(TEMPLATE_DIR, exist_ok=True)
    
    # 0 is always the default/blank option
    DYNAMIC_TEMPLATE_OPTIONS['0'] = {"name": "Default (Blank)", "file": None}
    
    count = 1
    # Iterate through files in the template directory
    for filename in os.listdir(TEMPLATE_DIR):
        if filename.endswith(".pptx"):
            # Use the filename (without extension) as the display name
            display_name = filename.replace(".pptx", "").replace("_", " ").title()
            
            # Store the full path and display name
            DYNAMIC_TEMPLATE_OPTIONS[str(count)] = {
                "name": display_name, 
                "file": os.path.join(TEMPLATE_DIR, filename)
            }
            count += 1
            
    return DYNAMIC_TEMPLATE_OPTIONS

def select_template():
    """Prompts the user to select a template from the dynamically loaded options."""
    global DYNAMIC_TEMPLATE_OPTIONS
    DYNAMIC_TEMPLATE_OPTIONS = load_template_options()
    
    print("\n--- 🎨 TEMPLATE SELECTION ---")
    if len(DYNAMIC_TEMPLATE_OPTIONS) == 1: # Only '0' (Default) is present
        print(f"No .pptx files found in the '{TEMPLATE_DIR}' folder.")

    for key, value in DYNAMIC_TEMPLATE_OPTIONS.items():
        status = " (Ready)" if value['file'] else ""
        print(f"{key}. {value['name']}{status}")
        
    while True:
        choice = input(f"Enter the number of the desired template (0-{len(DYNAMIC_TEMPLATE_OPTIONS) - 1}): ").strip()
        if choice in DYNAMIC_TEMPLATE_OPTIONS:
            return DYNAMIC_TEMPLATE_OPTIONS[choice].get('file')
        print("Invalid selection. Please try again.")

# --------------------------------
# MAIN LOOP
# --------------------------------
if __name__ == "__main__":
    print(f"🔹 Initializing...")
    
    if not API_KEY:
        API_KEY = input("🔑 Enter your Gemini API Key: ").strip()
        genai.configure(api_key=API_KEY)
        
    # --- STEP 0: Select Template ---
    selected_template_file = select_template()
    # Find the name of the selected file to print confirmation
    selected_name = "Default (Blank)"
    for key, value in DYNAMIC_TEMPLATE_OPTIONS.items():
        if value.get('file') == selected_template_file:
            selected_name = value['name']
            break
            
    print(f"Template chosen: {selected_name}")
    # -------------------------------

    txt_path = r"G:\Project\PDF_TO_TEXT\2_OpenCV_OCR\test_output\combined_output.txt"
    try:
        raw_text = read_text_file(txt_path)
        print(f"\n📖 Analyzed text. Designing structure...")
        current_structure_json = generate_initial_structure(raw_text)

        while True:
            valid_json = print_blueprint(current_structure_json)
            if not valid_json: break

            print("\nOPTIONS:")
            print("1. ✅ Approve & Generate PPT")
            print("2. 💬 Give instructions to modify")
            print("3. ❌ Exit")
            
            choice = input("\n👉 Your choice: ").strip().lower()

            if choice == '1' or choice == 'yes' or choice == 'approve':
                os.makedirs(OUTPUT_FOLDER, exist_ok=True)
                output_file = os.path.join(OUTPUT_FOLDER, "Final_Presentation.pptx")
                
                # Use the selected template file path
                create_pptx(current_structure_json, output_file, selected_template_file)
                break
                
            elif choice == '3' or choice == 'exit':
                break
            else:
                instruction = choice if len(choice) > 3 else input("💬 Instruction: ")
                print("\n🔄 Updating...")
                current_structure_json = update_structure(current_structure_json, instruction)
                
    except Exception as e:
        print(f"\n❌ Error: {e}")
