import os
import json
import google.generativeai as genai
from pptx import Presentation
from pptx.util import Inches, Pt

# --------------------------------
# CONFIGURATION
# --------------------------------
API_KEY = "AIzaSyAzHf66I6a1uHUbC1-PnFCK6KyBUZTOJYI"
MODEL_NAME = "models/gemini-2.5-flash"

genai.configure(api_key=API_KEY)
model = genai.GenerativeModel(MODEL_NAME) 

if API_KEY:
    genai.configure(api_key=API_KEY)

# --------------------------------
# HELPER: READ FILE
# --------------------------------
def read_text_file(path):
    if not os.path.exists(path):
        # Create dummy file for testing if missing
        with open("input.txt", "w") as f:
            f.write("Artificial Intelligence is changing the world. It helps in healthcare by diagnosing diseases. It helps in finance by detecting fraud. In the future, AI might become autonomous.")
        return read_text_file("input.txt")
        
    with open(path, "r", encoding="utf-8") as f:
        return f.read()

# --------------------------------
# CORE: GEMINI LOGIC
# --------------------------------
def get_ai_response(prompt):
    model = genai.GenerativeModel(MODEL_NAME)
    try:
        response = model.generate_content(prompt)
        text = response.text.strip()
        # Clean up markdown formatting if Gemini adds it
        if text.startswith("```json"):
            text = text.replace("```json", "").replace("```", "")
        return text
    except Exception as e:
        print(f"Error connecting to AI: {e}")
        return None

def generate_initial_structure(raw_text):
    prompt = f"""
    You are an expert presentation designer. 
    Analyze the following raw text and organize it into a structured PowerPoint presentation.
    
    RAW TEXT:
    {raw_text}
    
    RULES:
    1. Create suitable headings and subheadings.
    2. Expand on the content to make it presentation-ready (add relevant details if the raw text is brief).
    3. Output MUST be valid JSON format only. No extra text.
    4. Structure: A list of objects, where each object has "title" (string) and "content" (list of strings).
    
    Example Output Format:
    [
        {{"title": "Introduction", "content": ["Point 1", "Point 2"]}},
        {{"title": "Future Scope", "content": ["Point A", "Point B"]}}
    ]
    """
    return get_ai_response(prompt)

def update_structure(current_json, user_instruction):
    prompt = f"""
    You are editing a presentation structure based on user feedback.
    
    CURRENT STRUCTURE (JSON):
    {current_json}
    
    USER INSTRUCTION:
    "{user_instruction}"
    
    TASK:
    1. Modify the JSON structure according to the instruction.
    2. You can add slides, remove slides, or change content.
    3. Return ONLY the valid updated JSON.
    """
    return get_ai_response(prompt)

# --------------------------------
# DISPLAY & EXPORT
# --------------------------------
def print_blueprint(slides_data):
    """Prints a user-friendly preview of the slides"""
    print("\n" + "="*50)
    print(" 📊 PRESENTATION BLUEPRINT (PREVIEW)")
    print("="*50)
    
    try:
        data = json.loads(slides_data)
        for i, slide in enumerate(data, 1):
            print(f"\n[SLIDE {i}]: {slide['title']}")
            for bullet in slide['content']:
                print(f"  • {bullet}")
    except json.JSONDecodeError:
        print("Error reading the blueprint. AI returned invalid JSON.")
        print(slides_data) # Debug
        return False
    
    print("\n" + "="*50)
    return True

def create_pptx(slides_data, output_path):
    """Converts the JSON structure into an actual .pptx file"""
    try:
        data = json.loads(slides_data)
    except:
        print("❌ Failed to parse data for PPT generation.")
        return

    prs = Presentation()
    
    # 1. Create Title Slide (using the first item in JSON as title usually, or generic)
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = data[0]['title'] if data else "Presentation"
    subtitle.text = "Generated by Gemini AI"

    # 2. Create Content Slides
    bullet_slide_layout = prs.slide_layouts[1] # Title and Content layout
    
    for entry in data:
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        
        # Set Title
        title_shape = shapes.title
        title_shape.text = entry['title']
        
        # Set Bullets
        body_shape = shapes.placeholders[1]
        tf = body_shape.text_frame
        tf.word_wrap = True
        
        # Clear existing text
        tf.clear() 

        for point in entry['content']:
            p = tf.add_paragraph()
            p.text = point
            p.level = 0
            p.font.size = Pt(18) # Adjust font size

    prs.save(output_path)
    print(f"\n💾 Presentation saved successfully: {output_path}")

# --------------------------------
# MAIN LOOP
# --------------------------------
if __name__ == "__main__":
    if not API_KEY:
        API_KEY = input("🔑 Enter your Gemini API Key: ").strip()
        genai.configure(api_key=API_KEY)

    # 1. Load Text
    txt_path = r"G:\Project\PDF_TO_TEXT\2_OpenCV_OCR\test_output\combined_output.txt"
    raw_text = read_text_file(txt_path)
    print(f"\n📖 Read {len(raw_text)} characters. Analyzing content...")

    # 2. Initial Generation
    print("🧠 Gemini is designing the initial presentation structure...")
    current_structure_json = generate_initial_structure(raw_text)

    # 3. Interaction Loop
    while True:
        # Show the current plan
        valid_json = print_blueprint(current_structure_json)
        
        if not valid_json:
            print("❌ Critical Error in AI response. Restarting...")
            break

        print("\nOPTIONS:")
        print("1. ✅ Approve & Generate PPT")
        print("2. 💬 Give instructions to modify (e.g., 'Add a conclusion slide', 'Make slide 2 shorter')")
        print("3. ❌ Exit")
        
        choice = input("\n👉 Your choice: ").strip().lower()

        if choice == '1' or choice == 'yes' or choice == 'approve':
            output_file = r"G:\Project\PDF_TO_TEXT\5_Final_Outputs\Final_Presentation.pptx"
            create_pptx(current_structure_json, output_file)
            break
            
        elif choice == '3' or choice == 'exit':
            print("Exiting...")
            break
            
        else:
            # Assume user typed an instruction
            instruction = choice if len(choice) > 3 else input("💬 Enter your instruction: ")
            print("\n🔄 Gemini is updating the blueprint based on your feedback...")
            current_structure_json = update_structure(current_structure_json, instruction)